homepage:
    path:      /{_locale}
    defaults:  { _controller: BloggerBloggerBundle:Default:index, _locale: en}
    requirements:
        _locale:  fr|en
        methods:  GET
        schemes:  https
